### ISSUE TITLE
Setup svg-min

### ISSUE THREAD

**Issue by nt1m** [nt1m/firefox-svg-icons#3]

**Comment by helenvholmes** [comment]
I have a lazy-ish executable [here](https://github.com/helenvholmes/devtools-ux/blob/master/src/html/icons/clean-svg) that I've been using for cleaning up the panel icons, but it had a bunch of known problems that makes me think it's only useful for icons really:

- Only works with icons as Illustrator outputs them
- Works based on line, not intelligent pattern matching
